spring:
  application:
    name: NettyWrap
  datasource:
    url: jdbc:mysql://localhost:3306/testDB
    username: root
    password: ks24453944
    driver-class-name: com.mysql.cj.jdbc.Driver
  config:
    import:
      - tcpClientConfig.yml
      - tcpServerConfig.yml